
import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  // Spices
  {
    id: 'prod_ig_1',
    name: 'Turmeric Powder (Haldi)',
    description: 'Aromatic and vibrant turmeric powder, essential for Indian cooking. Known for its color and health benefits.',
    price: 3.99,
    imageUrl: 'https://picsum.photos/seed/turmericpowder/400/300',
    category: 'Spices',
    uom: '250g',
  },
  {
    id: 'prod_ig_2',
    name: 'Cumin Seeds (Jeera)',
    description: 'Whole cumin seeds, adding a warm, earthy flavor to dishes. Often used for tempering.',
    price: 4.49,
    imageUrl: 'https://picsum.photos/seed/cuminseeds/400/300',
    category: 'Spices',
    uom: '125g',
  },
  {
    id: 'prod_ig_3',
    name: 'Coriander Powder (Dhania)',
    description: 'Ground coriander powder, offering a mild, citrusy flavor. A staple in many spice blends.',
    price: 3.79,
    imageUrl: 'https://picsum.photos/seed/corianderpowder/400/300',
    category: 'Spices',
    uom: '250g',
  },
  {
    id: 'prod_ig_4',
    name: 'Garam Masala',
    description: 'A blend of ground spices, used to add warmth and complexity to a variety of Indian dishes.',
    price: 5.99,
    imageUrl: 'https://picsum.photos/seed/garammasala/400/300',
    category: 'Spices',
    uom: '125g',
  },
  {
    id: 'prod_ig_5',
    name: 'Red Chili Powder (Lal Mirch)',
    description: 'Fiery red chili powder for adding heat and color. Use sparingly for desired spice level.',
    price: 4.29,
    imageUrl: 'https://picsum.photos/seed/redchilipowder/400/300',
    category: 'Spices',
    uom: '250g',
  },
  {
    id: 'prod_ig_6',
    name: 'Green Cardamom Pods (Elaichi)',
    description: 'Whole green cardamom pods, intensely aromatic, used in sweets, savories, and beverages.',
    price: 7.99,
    imageUrl: 'https://picsum.photos/seed/cardamompods/400/300',
    category: 'Spices',
    uom: '125g',
  },
  {
    id: 'prod_ig_7',
    name: 'Cloves (Laung)',
    description: 'Aromatic flower buds with a strong, pungent flavor. Used in spice blends and rice dishes.',
    price: 6.49,
    imageUrl: 'https://picsum.photos/seed/cloves/400/300',
    category: 'Spices',
    uom: '125g',
  },
  {
    id: 'prod_ig_8',
    name: 'Mustard Seeds (Rai)',
    description: 'Small, pungent seeds used for tempering in South Indian and Bengali cuisine.',
    price: 3.29,
    imageUrl: 'https://picsum.photos/seed/mustardseeds/400/300',
    category: 'Spices',
    uom: '125g',
  },
  {
    id: 'prod_ig_9',
    name: 'Fenugreek Seeds (Methi Dana)',
    description: 'Slightly bitter seeds with a nutty aroma, used in pickles and tempering.',
    price: 3.99,
    imageUrl: 'https://picsum.photos/seed/fenugreekseeds/400/300',
    category: 'Spices',
    uom: '125g',
  },
  {
    id: 'prod_ig_10',
    name: 'Asafoetida (Hing)',
    description: 'A strong, pungent spice used in small quantities to add a savory, umami flavor. Gluten-free options available.',
    price: 5.79,
    imageUrl: 'https://picsum.photos/seed/asafoetida/400/300',
    category: 'Spices',
    uom: '125g',
  },

  // Lentils & Beans
  {
    id: 'prod_ig_11',
    name: 'Toor Dal (Arhar Dal)',
    description: 'Split pigeon peas, a staple lentil in Indian households, used for making dal tadka and sambar.',
    price: 6.99,
    imageUrl: 'https://picsum.photos/seed/toordal/400/300',
    category: 'Lentils & Beans',
    uom: '1kg',
  },
  {
    id: 'prod_ig_12',
    name: 'Masoor Dal (Red Lentils)',
    description: 'Split red lentils, cook quickly and are great for soups and simple dals.',
    price: 5.49,
    imageUrl: 'https://picsum.photos/seed/masoordal/400/300',
    category: 'Lentils & Beans',
    uom: '500g',
  },
  {
    id: 'prod_ig_13',
    name: 'Chana Dal (Split Chickpeas)',
    description: 'Split chickpeas with a nutty flavor, used in various curries, snacks, and sweets.',
    price: 6.29,
    imageUrl: 'https://picsum.photos/seed/chanadal/400/300',
    category: 'Lentils & Beans',
    uom: '1kg',
  },
  {
    id: 'prod_ig_14',
    name: 'Moong Dal (Split Mung Beans)',
    description: 'Split and skinned mung beans, easy to digest and versatile for both sweet and savory dishes.',
    price: 7.49,
    imageUrl: 'https://picsum.photos/seed/moongdal/400/300',
    category: 'Lentils & Beans',
    uom: '500g',
  },
  {
    id: 'prod_ig_15',
    name: 'Urad Dal (Split Black Gram)',
    description: 'Split black gram, often used for making idli, dosa batter, and dal makhani.',
    price: 6.79,
    imageUrl: 'https://picsum.photos/seed/uraddal/400/300',
    category: 'Lentils & Beans',
    uom: '500g',
  },
  {
    id: 'prod_ig_16',
    name: 'Rajma (Kidney Beans)',
    description: 'Red kidney beans, perfect for making the classic North Indian dish, Rajma Chawal.',
    price: 8.99,
    imageUrl: 'https://picsum.photos/seed/rajma/400/300',
    category: 'Lentils & Beans',
    uom: '1kg',
  },
  {
    id: 'prod_ig_17',
    name: 'Kabuli Chana (Chickpeas)',
    description: 'Whole white chickpeas, used for chole, hummus, and salads.',
    price: 7.99,
    imageUrl: 'https://picsum.photos/seed/kabulichana/400/300',
    category: 'Lentils & Beans',
    uom: '1kg',
  },
  {
    id: 'prod_ig_18',
    name: 'Lobia (Black Eyed Peas)',
    description: 'Creamy white beans with a black spot, used in curries and salads.',
    price: 6.49,
    imageUrl: 'https://picsum.photos/seed/lobia/400/300',
    category: 'Lentils & Beans',
    uom: '500g',
  },

  // Rice & Grains
  {
    id: 'prod_ig_19',
    name: 'Basmati Rice (Premium)',
    description: 'Long-grain aromatic rice, perfect for biryani, pulao, or as a side dish.',
    price: 15.99,
    imageUrl: 'https://picsum.photos/seed/basmatirice/400/300',
    category: 'Rice & Grains',
    uom: '25kg',
  },
  {
    id: 'prod_ig_20',
    name: 'Sona Masoori Rice',
    description: 'Medium-grain rice, popular in South India for everyday meals.',
    price: 12.99,
    imageUrl: 'https://picsum.photos/seed/sonamasoori/400/300',
    category: 'Rice & Grains',
    uom: '25kg',
  },
  {
    id: 'prod_ig_21',
    name: 'Idli Rice',
    description: 'Parboiled rice specifically for making soft and fluffy idlis and dosas.',
    price: 10.99,
    imageUrl: 'https://picsum.photos/seed/idlirice/400/300',
    category: 'Rice & Grains',
    uom: '1kg',
  },
  {
    id: 'prod_ig_22',
    name: 'Poha (Flattened Rice)',
    description: 'Flattened rice flakes, used for making a popular breakfast dish or light snack.',
    price: 4.99,
    imageUrl: 'https://picsum.photos/seed/poha/400/300',
    category: 'Rice & Grains',
    uom: '500g',
  },
  {
    id: 'prod_ig_23',
    name: 'Sooji (Semolina/Rava)',
    description: 'Coarse, purified wheat middlings, used for upma, halwa, and other dishes.',
    price: 3.99,
    imageUrl: 'https://picsum.photos/seed/sooji/400/300',
    category: 'Rice & Grains',
    uom: '1kg',
  },
  {
    id: 'prod_ig_24',
    name: 'Atta (Whole Wheat Flour)',
    description: 'Stone-ground whole wheat flour, essential for making chapatis, rotis, and parathas.',
    price: 9.99,
    imageUrl: 'https://picsum.photos/seed/attaflour/400/300',
    category: 'Rice & Grains',
    uom: '1kg',
  },
  {
    id: 'prod_ig_25',
    name: 'Besan (Gram Flour)',
    description: 'Flour made from ground chickpeas, used for pakoras, kadhi, and sweets like ladoo.',
    price: 5.29,
    imageUrl: 'https://picsum.photos/seed/besanflour/400/300',
    category: 'Rice & Grains',
    uom: '1kg',
  },

  // Snacks
  {
    id: 'prod_ig_26',
    name: 'Murukku (Chakli)',
    description: 'Crunchy, spiral-shaped savory snack made from rice flour and spices.',
    price: 4.79,
    imageUrl: 'https://picsum.photos/seed/murukku/400/300',
    category: 'Snacks',
    uom: '250g',
  },
  {
    id: 'prod_ig_27',
    name: 'Aloo Bhujia',
    description: 'Spicy and crispy noodle-like snack made from potato and gram flour.',
    price: 3.99,
    imageUrl: 'https://picsum.photos/seed/aloobhujia/400/300',
    category: 'Snacks',
    uom: '250g',
  },
  {
    id: 'prod_ig_28',
    name: 'Frozen Samosas (Vegetable)',
    description: 'Pack of frozen, ready-to-fry or bake vegetable samosas.',
    price: 7.99,
    imageUrl: 'https://picsum.photos/seed/samosafrozen/400/300',
    category: 'Snacks',
    uom: 'pcs',
  },
  {
    id: 'prod_ig_29',
    name: 'Khakhra (Methi)',
    description: 'Thin, crispy crackers made from whole wheat flour and fenugreek leaves.',
    price: 5.49,
    imageUrl: 'https://picsum.photos/seed/khakhra/400/300',
    category: 'Snacks',
    uom: '250g',
  },
  {
    id: 'prod_ig_30',
    name: 'Bhel Puri Mix',
    description: 'A kit containing puffed rice, sev, chutneys, and spices to make delicious Bhel Puri at home.',
    price: 6.99,
    imageUrl: 'https://picsum.photos/seed/bhelpurimix/400/300',
    category: 'Snacks',
    uom: '500g',
  },
  {
    id: 'prod_ig_31',
    name: 'Mathri',
    description: 'Flaky, savory biscuits, perfect with tea or as a light snack.',
    price: 4.99,
    imageUrl: 'https://picsum.photos/seed/mathri/400/300',
    category: 'Snacks',
    uom: '250g',
  },
  {
    id: 'prod_ig_32',
    name: 'Roasted Chana (Spiced)',
    description: 'Healthy and crunchy roasted chickpeas, lightly spiced.',
    price: 5.29,
    imageUrl: 'https://picsum.photos/seed/roastedchana/400/300',
    category: 'Snacks',
    uom: '250g',
  },

  // Beverages
  {
    id: 'prod_ig_33',
    name: 'Masala Chai Mix (Instant)',
    description: 'Instant tea premix with authentic Indian spices for a quick cup of masala chai.',
    price: 8.49,
    imageUrl: 'https://picsum.photos/seed/masalachaimix/400/300',
    category: 'Beverages',
    uom: '250g',
  },
  {
    id: 'prod_ig_34',
    name: 'Mango Lassi (Bottled)',
    description: 'Refreshing yogurt-based mango drink, ready to consume.',
    price: 3.99,
    imageUrl: 'https://picsum.photos/seed/mangolassi/400/300',
    category: 'Beverages',
    uom: '600mL',
  },
  {
    id: 'prod_ig_35',
    name: 'Rooh Afza Syrup',
    description: 'A concentrated squash with a unique flavor, often mixed with water or milk.',
    price: 9.99,
    imageUrl: 'https://picsum.photos/seed/roohafza/400/300',
    category: 'Beverages',
    uom: '1L',
  },
  {
    id: 'prod_ig_36',
    name: 'Filter Coffee Powder (South Indian)',
    description: 'Authentic South Indian filter coffee powder for a strong, aromatic brew.',
    price: 7.79,
    imageUrl: 'https://picsum.photos/seed/filtercoffee/400/300',
    category: 'Beverages',
    uom: '250g',
  },
  {
    id: 'prod_ig_37',
    name: 'Badam Milk Mix',
    description: 'A mix of almonds, cardamom, and saffron to make delicious almond milk.',
    price: 6.99,
    imageUrl: 'https://picsum.photos/seed/badammilk/400/300',
    category: 'Beverages',
    uom: '250g',
  },

  // Pantry Staples (Conceptual Fresh Produce)
  {
    id: 'prod_ig_38',
    name: 'Onions (1kg Bag)',
    description: 'Fresh red onions, a staple in most Indian cooking for base flavor.',
    price: 2.99,
    imageUrl: 'https://picsum.photos/seed/onions/400/300',
    category: 'Pantry Staples',
    uom: '1kg',
  },
  {
    id: 'prod_ig_39',
    name: 'Potatoes (1kg Bag)',
    description: 'Versatile potatoes, suitable for curries, fries, and various dishes.',
    price: 3.49,
    imageUrl: 'https://picsum.photos/seed/potatoes/400/300',
    category: 'Pantry Staples',
    uom: '1kg',
  },
  {
    id: 'prod_ig_40',
    name: 'Tomatoes (500g Pack)',
    description: 'Fresh ripe tomatoes, used for making gravies, salads, and sauces.',
    price: 2.79,
    imageUrl: 'https://picsum.photos/seed/tomatoes/400/300',
    category: 'Pantry Staples',
    uom: '500g',
  },
  {
    id: 'prod_ig_41',
    name: 'Ginger (250g)',
    description: 'Fresh ginger root, adds a pungent and spicy flavor to dishes.',
    price: 1.99,
    imageUrl: 'https://picsum.photos/seed/ginger/400/300',
    category: 'Pantry Staples',
    uom: '250g',
  },
  {
    id: 'prod_ig_42',
    name: 'Garlic (250g)',
    description: 'Fresh garlic bulbs, essential for its strong aroma and taste in Indian cuisine.',
    price: 2.29,
    imageUrl: 'https://picsum.photos/seed/garlic/400/300',
    category: 'Pantry Staples',
    uom: '250g',
  },

  // Dairy & Frozen
  {
    id: 'prod_ig_43',
    name: 'Paneer (Indian Cottage Cheese)',
    description: 'Fresh, non-melting Indian cottage cheese, perfect for curries and grilled dishes.',
    price: 6.99,
    imageUrl: 'https://picsum.photos/seed/paneer/400/300',
    category: 'Dairy & Frozen',
    uom: '250g',
  },
  {
    id: 'prod_ig_44',
    name: 'Pure Ghee (Clarified Butter)',
    description: 'Aromatic clarified butter, used for cooking, frying, and religious ceremonies.',
    price: 12.49,
    imageUrl: 'https://picsum.photos/seed/ghee/400/300',
    category: 'Dairy & Frozen',
    uom: '500g',
  },
  {
    id: 'prod_ig_45',
    name: 'Dahi (Plain Yogurt)',
    description: 'Fresh plain yogurt, a staple accompaniment to Indian meals or used in raitas.',
    price: 4.49,
    imageUrl: 'https://picsum.photos/seed/dahi/400/300',
    category: 'Dairy & Frozen',
    uom: '600mL',
  },
  {
    id: 'prod_ig_46',
    name: 'Kulfi (Pistachio Flavor - Frozen)',
    description: 'Traditional Indian ice cream with a rich pistachio flavor. Pack of 4.',
    price: 8.99,
    imageUrl: 'https://picsum.photos/seed/kulfi/400/300',
    category: 'Dairy & Frozen',
    uom: 'pcs',
  },
  {
    id: 'prod_ig_47',
    name: 'Frozen Parathas (Plain)',
    description: 'Pack of ready-to-cook plain parathas. Flaky and delicious.',
    price: 5.99,
    imageUrl: 'https://picsum.photos/seed/parathafrozen/400/300',
    category: 'Dairy & Frozen',
    uom: 'pcs',
  },

  // Ready to Eat
  {
    id: 'prod_ig_48',
    name: 'Palak Paneer (Ready to Eat)',
    description: 'A convenient ready-to-eat meal of spinach and cottage cheese curry.',
    price: 4.99,
    imageUrl: 'https://picsum.photos/seed/palakpaneerrte/400/300',
    category: 'Ready to Eat',
    uom: '250g',
  },
  {
    id: 'prod_ig_49',
    name: 'Dal Makhani (Ready to Eat)',
    description: 'Creamy and rich black lentils and kidney beans curry, ready to heat and serve.',
    price: 4.79,
    imageUrl: 'https://picsum.photos/seed/dalmakhanirte/400/300',
    category: 'Ready to Eat',
    uom: '250g',
  },
  {
    id: 'prod_ig_50',
    name: 'Vegetable Biryani (Ready to Eat)',
    description: 'Aromatic basmati rice cooked with mixed vegetables and spices. Just heat and enjoy.',
    price: 5.49,
    imageUrl: 'https://picsum.photos/seed/vegbiryanirte/400/300',
    category: 'Ready to Eat',
    uom: '250g',
  },
];

export const ISSUE_TYPES = [
  "Order Delay",
  "Missing Item",
  "Incorrect item",
  "Damaged item",
  "Incorrect quantity",
] as const;
